stages:
  - rebuild

variables:
  REBUILDER_MAINTAINER: "Paul Spooren"
  REBUILDER_CONTACT: "mail@aparcar.org"
  REBUILDER_NAME: "aparcar-openwrt-gitlab"
  REBUILDER_URI: "https://gitlab.com/aparcar/rebuild"
  DL_PATH: "./dl"
  USE_DIFFOSCOPE: 1

cache:
  paths:
  - ./dl

.rebuild:
  image:
    name: aparcar/rebuild-diffoscope
    entrypoint: [""]
  stage: rebuild
  script:
    - mkdir -p ./dl
    - python3 -u rebuild.py
  artifacts:
    paths:
      - results/
    expire_in: 1 week
  before_script:
    - export TARGET="$(echo ${CI_JOB_NAME} | cut -d '_' -f 2 | tr '-' '/')"

rebuild_ath79-generic: { extends: .rebuild }
rebuild_bcm47xx-generic: { extends: .rebuild }
rebuild_lantiq-xrx200: { extends: .rebuild }
rebuild_kirkwood-generic: { extends: .rebuild }
rebuild_omap-generic: { extends: .rebuild }
rebuild_ramips-mt7620: { extends: .rebuild }
rebuild_ramips-mt7621: { extends: .rebuild }
rebuild_rockchip-armv8: { extends: .rebuild }
rebuild_sunxi-cortexa8: { extends: .rebuild }
rebuild_tegra-generic: { extends: .rebuild }
rebuild_x86-64: { extends: .rebuild }
