name: Rebuild OpenWrt Snapshot

on:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - ath79/generic

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install libncurses-dev
      run: sudo apt-get install libncurses-dev

    - name: Run rebuilder on ${{ matrix.target }}
      run: python3 -u rebuild.py
      env:
        TARGET: ${{ matrix.target }}
        REBUILDER_MAINTAINER: "Paul Spooren"
        REBUILDER_CONTACT: "mail@aparcar.org"
        REBUILDER_NAME: "aparcar-openwrt-github"
        REBUILDER_URI: "https://github.com/aparcar/openwrt-rebuilder"

    - name: Cleanup build root
      run: rm -rf rebuild/staging_dir rebuild/build_dir

    - name: sanitize target
      run: echo ::set-env name=target_sani::$(echo ${{ matrix.target }} | tr "/" "_")

    - uses: actions/upload-artifact@v2
      with:
        name: results-snapshots-${{ env.target_sani }}
        path: results/
